hive> DROP TABLE IF EXISTS pokes;
hive> CREATE TABLE pokes (foo INT, bar STRING) PARTITIONED BY (ds STRING);
hive> LOAD DATA LOCAL INPATH '[[EXAMPLES]]/kv2.txt' OVERWRITE INTO TABLE pokes PARTITION (ds='2008-08-15');
Copying file: file:[[EXAMPLES]]/kv2.txt
hive> LOAD DATA LOCAL INPATH '[[EXAMPLES]]/kv3.txt' OVERWRITE INTO TABLE pokes PARTITION (ds='2008-08-08');
Copying file: file:[[EXAMPLES]]/kv3.txt
hive> SHOW PARTITIONS pokes;
cfs://null/user/hive/warehouse/pokes/ds=2008-08-08
cfs://null/user/hive/warehouse/pokes/ds=2008-08-15
hive> SELECT ds, count(*) FROM pokes group by ds;
2008-08-08	25
2008-08-15	500
hive> alter table pokes drop partition (ds='2008-08-08');
hive> SHOW PARTITIONS pokes;
cfs://null/user/hive/warehouse/pokes/ds=2008-08-15
hive> SELECT ds, count(*) FROM pokes group by ds;
2008-08-15	500
hive> LOAD DATA LOCAL INPATH '[[EXAMPLES]]/kv3.txt' OVERWRITE INTO TABLE pokes PARTITION (ds='2008-08-08');
Copying file: file:[[EXAMPLES]]/kv3.txt
hive> SHOW PARTITIONS pokes;
cfs://null/user/hive/warehouse/pokes/ds=2008-08-08
cfs://null/user/hive/warehouse/pokes/ds=2008-08-15
hive> SELECT ds, count(*) FROM pokes group by ds;
2008-08-08	25
2008-08-15	500
hive> DROP TABLE pokes;
hive> quit;
