hive> DROP TABLE IF EXISTS mixedCaSE;
hive> DROP TABLE IF EXISTS mixedCaSE_renamed;
hive> DROP TABLE IF EXISTS mixedCaSE_clike;
hive> DROP TABLE IF EXISTS mixedCaSE_ctas;
hive> CREATE TABLE mixedCaSE (foo INT, bar STRING) COMMENT 'table to test DDL ops' PARTITIONED BY (ds STRING) STORED AS TEXTFILE;
hive> LOAD DATA LOCAL INPATH '[[EXAMPLES]]/kv1.txt' OVERWRITE INTO TABLE mixedCaSE PARTITION (ds='2008-08-08');
Copying file: file:[[EXAMPLES]]/kv1.txt
hive> CREATE TABLE mixedCaSE_clike LIKE mixedCaSE;
hive> DESCRIBE mixedCaSE_clike;
foo	int	
bar	string	
ds	string	
hive> CREATE TABLE mixedCaSE_ctas as SELECT * FROM mixedCaSE;
hive> DESCRIBE mixedCaSE;
foo	int	
bar	string	
ds	string	
hive> ALTER TABLE mixedCaSE ADD COLUMNS (new_col1 INT);
hive> INSERT OVERWRITE TABLE mixedCaSE PARTITION (ds='2008-08-15') SELECT foo, bar, 333333333 FROM mixedCaSE_ctas WHERE ds='2008-08-08';
hive> ALTER TABLE mixedCaSE ADD COLUMNS (new_col2 STRING, new_col3 STRING COMMENT 'a comment');
hive> INSERT OVERWRITE TABLE mixedCaSE PARTITION (ds='2008-08-18') SELECT foo, bar, 12345678, 'new string to insert', '2011-05-07' FROM mixedCaSE WHERE ds='2008-08-18';
hive> ALTER TABLE mixedCaSE CHANGE new_col1 new_col1a STRING after new_col2;
hive> ALTER TABLE mixedCaSE CHANGE bar bar STRING FIRST;
hive> ALTER TABLE mixedCaSE CHANGE foo foo INT FIRST;
hive> SHOW PARTITIONS mixedCaSE;
hive> DESCRIBE mixedCaSE;
foo	int	
bar	string	
new_col2	string	
new_col1a	string	
new_col3	string	a comment
ds	string	
hive> SELECT count(*), ds FROM mixedCaSE GROUP BY ds;
hive> ALTER TABLE mixedCaSE RENAME TO mixedCaSE_renamed;
hive> DESCRIBE mixedCaSE_renamed;
foo	int	
bar	string	
new_col2	string	
new_col1a	string	
new_col3	string	a comment
ds	string	
hive> SHOW PARTITIONS mixedCaSE_renamed;
hive> DESCRIBE mixedCaSE_renamed;
foo	int	
bar	string	
new_col2	string	
new_col1a	string	
new_col3	string	a comment
ds	string	
hive> SELECT ds, COUNT(*) FROM mixedCaSE_renamed GROUP BY ds;
hive> DROP TABLE mixedCaSE_renamed;
hive> DROP TABLE mixedCaSE_clike;
hive> DROP TABLE mixedCaSE_ctas;
hive> quit;
