hive> DROP TABLE IF EXISTS clike_target_table;
hive> DROP TABLE IF EXISTS clike_source_table;
hive> CREATE TABLE clike_source_table (foo INT, bar STRING) COMMENT 'Source Table for Create Like' PARTITIONED BY (ds STRING) STORED AS TEXTFILE;
hive> LOAD DATA LOCAL INPATH '[[EXAMPLES]]/kv1.txt' OVERWRITE INTO TABLE clike_source_table PARTITION (ds='2008-08-08');
Copying file: file:[[EXAMPLES]]/kv1.txt
hive> SELECT COUNT(*) FROM clike_source_table;
500
hive> CREATE TABLE clike_target_table LIKE clike_source_table;
hive> LOAD DATA LOCAL INPATH '[[EXAMPLES]]/kv2.txt' OVERWRITE INTO TABLE clike_target_table PARTITION (ds='2008-08-15');
Copying file: file:[[EXAMPLES]]/kv2.txt
hive> SELECT ds, COUNT(*) FROM clike_target_table group by ds;
2008-08-15	500
hive> DROP TABLE clike_target_table;
hive> DROP TABLE clike_source_table;
hive> quit;
