hive> DROP TABLE IF EXISTS ctas_source_table;
hive> DROP TABLE IF EXISTS ctas_target_table;
hive> CREATE TABLE ctas_source_table (foo INT, bar STRING) COMMENT 'table to test CTAS';
hive> LOAD DATA LOCAL INPATH '[[EXAMPLES]]/kv1.txt' OVERWRITE INTO TABLE ctas_source_table;
Copying file: file:[[EXAMPLES]]/kv1.txt
Deleted cfs://null/user/hive/warehouse/ctas_source_table
hive> SELECT COUNT(*) FROM ctas_source_table;
500
hive> CREATE TABLE ctas_target_table as SELECT * FROM ctas_source_table;
hive> SELECT COUNT(*) FROM ctas_target_table;
500
hive> DROP TABLE ctas_target_table;
hive> DROP TABLE ctas_source_table;
hive> quit;
