hive> DROP TABLE IF EXISTS table_a;
hive> CREATE TABLE table_a (foo INT, bar STRING) COMMENT 'table to test DDL ops' PARTITIONED BY (ds STRING) STORED AS TEXTFILE;
hive> LOAD DATA LOCAL INPATH '[[EXAMPLES]]/kv1.txt' OVERWRITE INTO TABLE table_a PARTITION (ds='2008-08-15');
Copying file: file:[[EXAMPLES]]/kv1.txt
hive> LOAD DATA LOCAL INPATH '[[EXAMPLES]]/kv2.txt' OVERWRITE INTO TABLE table_a PARTITION (ds='2008-08-08');
Copying file: file:[[EXAMPLES]]/kv2.txt
hive> SELECT ds, COUNT(*) FROM table_a GROUP BY ds;
2008-08-08	500
2008-08-15	500
hive> DROP TABLE IF EXISTS table_a;
hive> quit;
