-- Statement: DROP TABLE IF EXISTS u_genre
-- Statement: CREATE TABLE u_genre (genre STRING, count INT) ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' STORED AS TEXTFILE
-- Statement: LOAD DATA LOCAL INPATH '[[DATA_DIR]]/u.genre' OVERWRITE INTO TABLE u_genre
-- Statement: SELECT * FROM u_genre ORDER BY genre
, null, 
Action, 1, 
Adventure, 2, 
Animation, 3, 
Children's, 4, 
Comedy, 5, 
Crime, 6, 
Documentary, 7, 
Drama, 8, 
Fantasy, 9, 
Film-Noir, 10, 
Horror, 11, 
Musical, 12, 
Mystery, 13, 
Romance, 14, 
Sci-Fi, 15, 
Thriller, 16, 
War, 17, 
Western, 18, 
unknown, 0, 
