demos/portfolio_manager/portfolio.jar usr/share/brisk-demos/portfolio_manager
demos/portfolio_manager/bin usr/share/brisk-demos/portfolio_manager
demos/portfolio_manager/resources usr/share/brisk-demos/portfolio_manager
demos/portfolio_manager/thrift usr/share/brisk-demos/portfolio_manager
demos/portfolio_manager/website usr/share/brisk-demos/portfolio_manager
demos/portfolio_manager/README.txt usr/share/brisk-demos/portfolio_manager
demos/portfolio_manager/10_day_loss.q usr/share/brisk-demos/portfolio_manager
demos/pig/files/example.txt
demos/pig/push-to-cf.pig
demos/pig/sort-by-total-cfs.pig
demos/pig/sort-by-total-cs.pig
