-- Statement: use cqldb
-- Statement: DROP KEYSPACE testcql1
-- Statement: CREATE KEYSPACE testcql1 with strategy_class = 'SimpleStrategy' and strategy_options:replication_factor=1
-- Statement: use testcql1
-- Statement: use default
-- Statement: DROP KEYSPACE testcql1
-- Statement: CREATE KEYSPACE testcql1 with strategy_class =  'org.apache.cassandra.locator.SimpleStrategy' and strategy_options:replication_factor=1
-- Statement: use testcql1
-- Statement: use default
-- Statement: CREATE KEYSPACE testcql1 with strategy_class =  'org.apache.cassandra.locator.SimpleStrategy' and strategy_options:replication_factor=1
java.sql.SQLException: Keyspace already exists.
-- Statement: use default
-- Statement: DROP KEYSPACE testcql1
-- Statement: use testcql1
-- Statement: CREATE KEYSPACE testcql0
java.sql.SQLException: line 0:-1 mismatched input '<EOF>' expecting K_WITH
-- Statement: CREATE KEYSPACE ks-error with replication_factor = 1 and strategy_class = 'org.apache.cassandra.locator.SimpleStrategy'
java.sql.SQLException: line 1:18 mismatched input '-' expecting K_WITH
-- Statement: CREATE KEYSPACE bad-chars.~!^@| with strategy_class =  'org.apache.cassandra.locator.SimpleStrategy' and strategy_options:replication_factor=1
java.sql.SQLException: line 1:30 no viable alternative at character '|'
