-- Statement: USE cqldb
-- Statement: TRUNCATE users
-- Statement: INSERT INTO users (KEY, password) VALUES ('user1', 'ch@ngem3a')
-- Statement: INSERT INTO users (KEY, password) VALUES ('user1', 'ch@ngem3a')
-- Statement: INSERT INTO users (KEY, password, gender, state, birth_year) VALUES ('user1', 'ch@ngem3', 'f', 'TX', '1968')
-- Statement: INSERT INTO users (KEY, password) VALUES ('user2', 'ch@ngem3b')
-- Statement: INSERT INTO users (KEY, password) VALUES ('user3', 'ch@ngem3c')
-- Statement: INSERT INTO users (KEY, password) VALUES ('user4', 'ch@ngem3d')
-- Statement: INSERT INTO users (KEY, password) VALUES ('user5', 'ch@ngem3e')
-- Statement: INSERT INTO users (KEY, password) VALUES ('user6', 'ch@ngem3f')
-- Statement: INSERT INTO users (KEY, password) VALUES ('user7', 'ch@ngem3g')
-- Statement: INSERT INTO users (KEY, password) VALUES ('user8', 'ch@ngem3h')
-- Statement: INSERT INTO users (KEY, password) VALUES ('user9', 'ch@ngem3i')
-- Statement: INSERT INTO users (KEY, password) VALUES ('user10', 'ch@ngem3c')
-- Statement: INSERT INTO users (KEY, password) VALUES ('user11', 'ch@ngem3d')
-- Statement: INSERT INTO users (KEY, password) VALUES ('user12', 'ch@ngem3e')
-- Statement: INSERT INTO users (KEY, password) VALUES ('user13', 'ch@ngem3f')
-- Statement: INSERT INTO users (KEY, password) VALUES ('user14', 'ch@ngem3g')
-- Statement: SELECT * FROM users
user11, ch@ngem3d, 
user5, ch@ngem3e, 
user14, ch@ngem3g, 
user1, 1968, f, ch@ngem3, TX, 
user12, ch@ngem3e, 
user13, ch@ngem3f, 
user7, ch@ngem3g, 
user4, ch@ngem3d, 
user6, ch@ngem3f, 
user10, ch@ngem3c, 
user3, ch@ngem3c, 
user8, ch@ngem3h, 
user9, ch@ngem3i, 
user2, ch@ngem3b, 
